# Generated by Django 5.2.6 on 2025-10-07 20:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step', models.IntegerField()),
                ('input_payload', models.JSONField()),
                ('output_text', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OnboardingSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('current_step', models.IntegerField(default=1)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='IdeaDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem_text', models.TextField()),
                ('generated_idea', models.TextField(blank=True, null=True)),
                ('ai_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idea_draft', to='onboarding.airesponse')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.onboardingsession')),
            ],
        ),
        migrations.AddField(
            model_name='airesponse',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='onboarding.onboardingsession'),
        ),
    ]
